import { ResultSetHeader, RowDataPacket } from "mysql2/promise";

export type LanguageToSQLSuccessResponse = {
  status: "success";
  question: string; // The user's natural language query
  sqlStatement: string; // The SQL statement generated by OpenAI
  formattedAnswer: string; // The formatted, user-friendly answer generated by OpenAI
  rawData: RowDataPacket[] | ResultSetHeader; // The raw data returned from the SQL query
};

export type LanguageToSQLErrorResponse = {
  status: "error";
  errorCode:
    | "NO_QUERY_ERR" // When no query is provided in the request
    | "PROCESSING_ERR" // For errors during OpenAI or SQL processing
    | "UNSUPPORTED_QUERY_ERR" // When the query is not a SELECT statement
    | "DATABASE_ERR" // When there is a database-related error
    | "AI_PROCESSING_ERROR";
};

const errorMessagesMap: Record<
  LanguageToSQLErrorResponse["errorCode"],
  string
> = {
  NO_QUERY_ERR: "Nie podano zapytania. Proszę spróbować ponownie.",
  PROCESSING_ERR:
    "Wystąpił błąd podczas przetwarzania zapytania. Spróbuj ponownie później.",
  UNSUPPORTED_QUERY_ERR:
    "Zapytanie jest nieobsługiwane. Proszę upewnić się, że jest to zapytanie SELECT.",
  DATABASE_ERR: "Wystąpił problem z bazą danych. Spróbuj ponownie później.",
  AI_PROCESSING_ERROR:
    "Wystąpił błąd podczas przetwarzania AI. Spróbuj ponownie później.",
};

export function getUserFriendlyMessage(
  errorCode: LanguageToSQLErrorResponse["errorCode"]
): string {
  return (
    errorMessagesMap[errorCode] ||
    "Wystąpił nieoczekiwany błąd. Proszę spróbować ponownie."
  );
}

export type LanguageToSQLResponse =
  | LanguageToSQLSuccessResponse
  | LanguageToSQLErrorResponse;
